apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-controller-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - update
  - apiGroups:
      - freshrss.demo.openshift.com/v1alpha1
    resources:
      - FreshRSS
    verbs:
      - get
      - list
      - create
      - patch
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-controller-role
subjects:
  - kind: ServiceAccount
    name: tenant-controller-sa
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-controller
  namespace: default
  labels:
    app.kubernetes.io/name: rss-feed-tenant-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rss-feed-tenant-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rss-feed-tenant-controller
    spec:
      serviceAccountName: tenant-controller-sa
      containers:
        - name: rss-feed-tenant-controller
          image: quay.io/jnirosha/rss-feed-tenant-manager:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rss-feed-tenant-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tenant-controller-route
  namespace: default
spec:
  to:
    kind: Service
    name: tenant-controller-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None