apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-controller-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - freshrss.demo.openshift.com
    resources:
      - freshrsses
    verbs:
      - get
      - list
      - create
      - delete
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-controller-role
subjects:
  - kind: ServiceAccount
    name: tenant-controller-sa
    namespace: default

---

apiVersion: v1
kind: Secret
metadata:
  name: tenant-controller-mysql-password
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: redhat

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenant-controller-mysql-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tenant-controller-mysql-password
                  key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mysql-store
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-db-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-controller
  namespace: default
  labels:
    app.kubernetes.io/name: rss-feed-tenant-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rss-feed-tenant-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rss-feed-tenant-controller
    spec:
      serviceAccountName: tenant-controller-sa
      containers:
        - name: rss-feed-tenant-controller
          image: quay.io/jnirosha/rss-feed-tenant-manager:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tenant-controller-mysql-password
                  key: MYSQL_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rss-feed-tenant-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tenant-controller-route
  namespace: default
spec:
  to:
    kind: Service
    name: tenant-controller-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None